version: '3.7'

services:
  django-android:
    restart: always
    build: .
    container_name: django-android
   # env_file: .core/.env
    ports:
      - "80:8000"
    volumes:
      - .:/app
      - /app:/app
    working_dir: /app
    networks:
      - network-android
    depends_on:
      - mysql-android
      - phpmyadmin-android

  mysql-android:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password  
    container_name: mysql-android
    volumes:
      - ./database_data:/var/lib/mysql
    expose:
      - "3306"
    restart: unless-stopped
    env_file: .env 
    networks:
      - network-android
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}   

  phpmyadmin-android:
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin-android
    restart: unless-stopped   
    ports:      
      - 127.0.0.1:8085:80        
    environment:
      PMA_HOST: mysql-android
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD} 
      # PMA_AUTH_TYPE: cookie   # Agrega esta línea para habilitar la autenticación basada en cookies
    networks:
      - network-android
    depends_on:
      - mysql-android

networks:
  network-android:
    driver: bridge
